packages:
  - www
  - examples/**

overrides:
  '@langchain/community@<0.3.3': '>=0.3.3'
  ai@<5.0.52: '>=5.0.52'
  axios@>=1.0.0 <1.12.0: '>=1.12.0'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  jsondiffpatch@<0.7.2: '>=0.7.2'
  jws@<3.2.3: '>=3.2.3'
  langchain@<0.2.19: '>=0.2.19'
  next@>=15.0.0 <=15.4.4: '>=15.4.5'
  next@>=15.0.0-canary.0 <15.4.7: '>=15.4.7'
  next@>=15.3.0 <15.3.3: '>=15.3.3'
  next@>=15.3.0-canary.0 <15.3.6: '>=15.3.6'
  nodemailer@<7.0.7: '>=7.0.7'
  nodemailer@<=7.0.10: '>=7.0.11'
  playwright@<1.55.1: '>=1.55.1'
  prismjs@<1.30.0: '>=1.30.0'
  tar-fs@>=2.0.0 <2.1.3: '>=2.1.3'
  tar-fs@>=2.0.0 <2.1.4: '>=2.1.4'
  yargs-parser@>=6.0.0 <13.1.2: '>=13.1.2'
