service: lambda-drizzle
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: app.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-esbuild