service: lambda-db-pinger
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}


functions:
  rateHandler:
    handler: index.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
# Uncomments if you want to run the function every 2nd minute from Mon-Fri
#  cronHandler:
#    handler: index.run
#    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
#      - schedule: cron(0/2 * ? * MON-FRI *)
