name = "nile_drizzle_example"
main = "src/app.ts"
compatibility_date = "2024-12-06"
compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

# [vars]
# DATABASE_URL = "postgres://01939840-ef4a-76d9-b78c-b0489190388f:b63b043d-c81b-45b8-bade-35ea02ebc480@us-west-2.db.dev.thenile.dev/niledb_indigo_house"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1