# Generated by Django 5.0.6 on 2024-06-12 02:43

import todolist.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.UUID('90f6d6e0-15d3-45cf-b404-178794ef00e8'), primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('family_name', models.TextField(blank=True, null=True)),
                ('given_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('picture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a8b0e9cb-cc22-4d5b-8fdc-1059a2e2bc0c'), primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TenantUsers',
            fields=[
                ('tenant_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('roles', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tenant_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('53fba599-0b10-485a-9a91-49dbb7cd6ca8'), primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=todolist.models.one_week_hence)),
            ],
            options={
                'db_table': 'todos',
                'ordering': ['due_date'],
                'managed': False,
            },
        ),
    ]
