import './globals.css';
import type { Metadata } from 'next';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import NextJS from '../public/vercel.svg';
import Link from 'next/link';
import Logo from '../components/ui/logo';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Example App with Nile and Next.js',
  description: 'Generated by create next app',
};

function Card({ children }: { children: React.JSX.Element }) {
  return (
    <div className="w-60 rounded-lg border border-gray-600 p-4 transition-all hover:border-gray-700 hover:shadow-lg">
      {children}
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen flex-col items-center">
          <div className="border-b-px flex w-full flex-row items-center justify-between bg-black px-6 py-4">
            <div>
              <Image
                src={NextJS}
                alt="Next.js Logo"
                className=""
                height={24}
                width={100}
              />
            </div>
            <div>
              <a
                href="https://thenile.dev"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="flex flex-row items-center gap-3 text-white">
                  Created by <Logo className="h-10" />
                </div>
              </a>
            </div>
          </div>
          <div className="flex max-w-3xl flex-1 flex-col">
            <div className="mb-10 mt-20 text-center text-4xl">
              Email verification example
            </div>
            {children}
          </div>
          <div className="flex flex-row justify-between gap-8 p-8">
            <Card>
              <Link
                href="https://www.thenile.dev/docs/getting-started/languages/nextjs"
                target="_blank"
                rel="noopener"
                className="flex flex-col items-start gap-5"
              >
                <Logo fill="black" className="h-10" />
                Getting started guide
              </Link>
            </Card>

            <Card>
              <Link
                href="https://thenile.dev"
                target="_blank"
                rel="noopener"
                className="flex flex-col items-start gap-5"
              >
                <Logo fill="black" className="h-10" />
                Sign up to Nile
              </Link>
            </Card>

            <Card>
              <Link
                href="https://www.thenile.dev/templates"
                target="_blank"
                rel="noopener"
                className="flex flex-col items-start gap-5"
              >
                <Logo fill="black" className="h-10" />
                Try additional templates
              </Link>
            </Card>
          </div>
        </main>
      </body>
    </html>
  );
}
