/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/R4VhZjJkSvo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { Progress } from "@/components/ui/progress"

export function LandingComponent() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-4">
      <div className="text-center">
        <h1 className="text-4xl font-bold">SREAssistant</h1>
        <p className="mt-2 text-lg">Let AI write postmortems, debug outages and help reduce your MTTR</p>
      </div>
      <div className="flex items-center justify-center mt-8 space-x-4">
        <p>Login to your organization</p>
        <Button>Login</Button>
      </div>
      <div className="mt-12 text-center">
        <h2 className="text-2xl font-semibold">Assisting world class companies</h2>
      </div>
      <div className="mt-8">
        <Button variant="outline" className="w-full max-w-md">
          Chat with AI to learn about recent outages across companies
        </Button>
      </div>
      <div className="mt-8 space-y-4 w-full max-w-md">
        <div className="flex items-center justify-between">
          <p>Vercel -</p>
          <Progress value={70} className="w-3/4 bg-purple-500" />
        </div>
        <div className="flex items-center justify-between">
          <p>Replit -</p>
          <Progress value={70} className="w-3/4 bg-purple-500" />
        </div>
        <div className="flex items-center justify-between">
          <p>Fly.io -</p>
          <Progress value={70} className="w-3/4 bg-purple-500" />
        </div>
      </div>
    </div>
  )
}
