/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zA7RV15zIuT
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"
import { CartesianGrid, XAxis, Line, LineChart } from "recharts"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"

export function PostLogin() {
  return (
    <div className="flex h-screen">
      <aside className="w-64 border-r">
        <div className="p-4 text-lg font-bold border-b">SREAssistant</div>
        <nav className="flex flex-col p-4 space-y-4">
          <Button variant="ghost" className="justify-start">
            Postmortems
          </Button>
          <Button variant="ghost" className="justify-start">
            Debug
          </Button>
          <Button variant="ghost" className="justify-start">
            Support
          </Button>
          <Button variant="ghost" className="justify-start">
            Settings
          </Button>
        </nav>
      </aside>
      <main className="flex-1 p-8">
        <header className="flex justify-end p-4 text-lg font-bold border-b">Ram</header>
        <section className="p-8">
          <h1 className="mb-4 text-2xl font-bold">Things that happened since you last logged in</h1>
          <p className="mb-4">
            We had multiple production issues. Here is a detailed analysis about them and recommended next steps you can
            take.
          </p>
          <div className="mb-4">
            <p>dlhlinaodlnaodn</p>
            <p>dalhjlajldajldjdoajdoajdoiajdoihjoad</p>
            <p>laodjlaodjdoajdijoadla</p>
            <p>ljadljdoalijladljdaljlad</p>
            <p>daodla</p>
          </div>
          <div className="mb-4">
            <p>adjaldfjldjlaijldajldjaljda</p>
            <p>lajdlajdladjladj</p>
            <p>laodjlaodjaad</p>
          </div>
          <LinechartChart className="w-full h-64" />
        </section>
      </main>
    </div>
  )
}

function LinechartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
      >
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line dataKey="desktop" type="natural" stroke="var(--color-desktop)" strokeWidth={2} dot={false} />
        </LineChart>
      </ChartContainer>
    </div>
  )
}
