import { Inter } from 'next/font/google';
import Image from 'next/image';

import './globals.css';
import Link from 'next/link';
import Logo from '../components/ui/logo';
import NextJS from '../public/next.svg';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Card({ children }: { children: JSX.Element }) {
  return (
    <div className="w-60 rounded-lg border border-gray-600 p-4 transition-all hover:border-gray-700 hover:shadow-lg">
      {children}
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen flex-col items-center">
          <div className="border-b-px flex w-full flex-row items-center justify-between bg-black px-6 py-4">
            <div>
              <Image
                src={NextJS}
                alt="Next.js Logo"
                className="invert"
                height={24}
                width={100}
              />
            </div>
            <div className="text-3xl text-white">Email Login Example</div>
            <div>
              <a
                href="https://thenile.dev"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="flex flex-row items-center gap-3 text-white">
                  Created by <Logo className="h-10" />
                </div>
              </a>
            </div>
          </div>
          <div className="flex max-w-3xl flex-1 flex-col">{children}</div>
          <div className="flex flex-row justify-between gap-8 p-8">
            <Card>
              <Link
                href="https://www.thenile.dev/docs/user-authentication/email-login/nextjs"
                target="_blank"
                rel="noopener"
                className="flex h-full flex-col justify-between gap-5"
              >
                <Image
                  src={NextJS}
                  alt="Next.js Logo"
                  className=""
                  height={24}
                  width={100}
                />
                <div>Getting started guide</div>
              </Link>
            </Card>

            <Card>
              <Link
                href="https://console.thenile.dev"
                target="_blank"
                rel="noopener"
                className="flex flex-col items-start gap-5"
              >
                <Logo fill="black" className="h-10" />
                Sign up to Nile
              </Link>
            </Card>

            <Card>
              <Link
                href="https://www.thenile.dev/templates"
                target="_blank"
                rel="noopener"
                className="flex flex-col items-start gap-5"
              >
                <Logo fill="black" className="h-10" />
                Try additional templates
              </Link>
            </Card>
          </div>
        </main>
      </body>
    </html>
  );
}
